### ISSUE TITLE
[Bug] Issues with the message "preview"

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#103]
- very spammy
  * large embed
  * reply
  * no character/line limits

- no way for regular members to get rid of it
  * stays if either messages (and even both) are deleted - can be bad if someone links a message you don't really want public (and/or forgot to delete) 
  * no way to opt out (like you can with normal embeds by putting \<\> around the link)
  * someone suggested reactions to delete but that'd just make it even *larger*

**Comment by elkowar** [comment]
## making the embed smaller
We could just remove the "Quote of ..." footer, and replace it with a simple
```
golang sucks
  ~ ElKowar, <date>
```
That would look a lot less clean imo, but I do see the issue of spammy embeds in general

## Reply
Making it not reply would make the message noticably smaller, but would also remove a lot of the context to it. Do we want that? I don't know 👀 

## no character/line limit
I don't think that was actually ever an issue yet,.... And I can see people want to use this feature _specifically_ for longer messages they sent before, too. Thus, not sure if a line/character limit is actually sensible here.


## Deleting the messages should delete the embed
Theoretically? Yes, definitely. Practically? Rather difficult to implement, especially the "on deletion of the linked message" part - I have no way of really doing this other than keeping track of all embedded messages for ever, and checking through all of them on every message deletion,.... that would quickly become _a lot_ of messages. maybe a time-limited cache would be an option, but only if we deem this to be a more serious issue. (time limited as in, keep track of message links within the last 24 hours or so, and check all of those on every message deletion).

## No way to opt out
Yes, that could and should definitely be fixed - supporting <`link`> is a simple solution that I'll definitely do!

## Reaction to delete
Yea, no, even more spammy and not relevant in most cases

**Comment by 6gk** [comment]
> Making it not reply would make the message noticably smaller, but would also remove a lot of the context to it. Do we want that? I don't know :eyes: 

it's a lose-lose situation tbh

With the reply it's showing the link (and probably more) twice (duplicated information),  
without the reply it can be a tad unclear if multiple links are posted.

> deleting thing: Theoretically? Yes, definitely. Practically? Rather difficult to implement

Yeah, fair enough.  This is one of the things which is always iffy about message quoters.

> reaction to yeet: Yea, no, even more spammy and not relevant in most cases

Agree, but if there's one way it could work is if the poster has to add the reaction themself, instead of just tapping it (when the bot has already added it).  And there'd probably have to be a time limit for watching that too, of course.

**Comment by elkowar** [comment]
Reaction to yeet wouldn't require watching, that would be doable without issues (as long as the quoting person is somehow mentioned in there) - but which reaction? that's super unclear and I'd not really be a fan of that,...

Deleting,... yea, it's iffy, but I think it practically won't be an issue, I'd think.

I'd keep the reply for now... Should I do the 
```
> message
  ~ person
```
format instead of using the header? Would definitely look less clean, but ehhhhhhhhhh

**Comment by 6gk** [comment]
> but which reaction?
![image](https://user-images.githubusercontent.com/40295114/116812919-9cda6500-ab94-11eb-86e4-330cf5b779a1.png)

> that's super unclear and I'd not really be a fan of that,...

Yeah, it'll be a tad undocumented..

**Comment by elkowar** [comment]
I mean, by "which reaction" i meant "how would users know". As soon as we add a "react with ❌ to delete this" to the message we gain nothing again..... I think deletion isn't really feasible.

**Comment by 6gk** [comment]
> I mean, by "which reaction" i meant "how would users know".

Exactly what I mean by undocumented.

Make it word-of-mouth.

**Comment by elkowar** [comment]
So current state:

- DO: Dont send message quote embed if message link is surrounded in `<>`
- ASK COMMUNITY: remove author header and replace with more simple single line format
- TO BE DISCUSSED: delete embed if quoter reacts with ❌
    (Would anyone ever know or use this? Seems like a good idea in theory that very very rarely would actually be used)
- TO BE DISCUSSED: keep cache of message quotes within the last 24 hours, to check if the quoted or quoting message where deleted. If so, delete embed.
  - Non-trivial feature
  - unsure how often this is actually  an issue. Cant think of a case where a message was quoted, then deleted, and anyone had an issue with that.
  - implementation may require features that could be generalized much more, possibly even into something like having the bot support editing your message and it re-evaluating its command. Thus, if desired, maybe still wait until it is clearer if that generalized solution would be useful.

**Comment by elkowar** [comment]
Implemented <url> links being ignored in a6d945f

**Comment by 6gk** [comment]
sigk

**Comment by elkowar** [comment]
Are these to be discussed todos still relevant?

**Comment by 6gk** [comment]
I guess not, but it'd be nice to check for `<>` / link being removed when editing.
