### ISSUE TITLE
[BUG] Repo name still wrong

### ISSUE THREAD

**Issue by buffet** [unixporn/robbb#110]
## Expected behaviour
My eyes don't bleed

## Current behaviour
They do

**Comment by 6gk** [comment]
LGTM, it's not r****

**Comment by elkowar** [comment]
Fixed, repo still needs to be updated in code tho

**Comment by 6gk** [comment]
![:salute:](https://cdn.discordapp.com/emojis/566762856117436440.png)

![image](https://user-images.githubusercontent.com/40295114/118060911-3399f380-b3d7-11eb-9f3d-125f53888da7.png)
