### ISSUE TITLE
[FEATURE] Rename trup.db to robbb.db

### ISSUE THREAD

**Issue by Jimmysit0** [unixporn/robbb#113]
I'm not sure if this is possible, or an unnecessary change, but I think it would be better to be called robbb.db since the bot is robbb, not trup. I understand that this is just trup rewrite, but why should that be called trup.db (I found that files on .gitignore)

**Comment by elkowar** [comment]
it's just an ignored file from the dev side, nothing used in the project or in production. doesn't matter.
