### ISSUE TITLE
[FEATURE] Ban suggestion on behalf od sweets

### ISSUE THREAD

**Issue by manderio** [unixporn/robbb#115]
## Is your feature request related to a problem? Please describe.
Mobile users are slow at banning 

## Proposed feature
Have robbb watch message reactions. So if mods react with a :banban: emote or something, robbb just bans the user. That way mods don’t have to @ the user, or get the id, it can be done programmatically

## Additional context
This issue was submitted on behalf of @Sweets

additionally, as always, here's a [hug](https://tenor.com/sQkA.gif)!

**Comment by elkowar** [comment]
Really not a fan, as it's not infeasible for some mod to accidentally use that reaction on some unrelated message - either as a joke without thinking, or just as a typo and a too quick return press. The gain in efficiency is _minimal_, and the risk is pretty high.

**Comment by manderio** [comment]
I do agree with you. While having a nicer way to ban on mobile would be nice, this really isn't ideal. It would also restrict mods from just joke around with reactions. Reason I brought up the issue is more so that it could be discussed :D

**Comment by elkowar** [comment]
Yea, don't think this is a good idea, and most people seem to agree. let's close this! Thanks though!
