### ISSUE TITLE
[BUG] !poll reactions get removed

### ISSUE THREAD

**Issue by L3afMe** [unixporn/robbb#119]
## Expected behaviour
Poll reactions stay after voting

## Current behaviour
After someone votes on the poll, the bot removes it's own reactions. This only seems to happen in ricing-theming.

**Comment by mlvzk** [comment]
sus

**Comment by mTvare6** [comment]
It's a mod doing this 🔫

**Comment by L3afMe** [comment]
@mTvare6 Free issue on my profile if so

**Comment by 6gk** [comment]
i think this was user error
