### ISSUE TITLE
[FEATURE] Either add time to database or don't show time for !fetch and !tag

### ISSUE THREAD

**Issue by elkowar** [unixporn/robbb#125]
## Is your feature request related to a problem? Please describe.
currently, !tag and !fetch show a time - the time of posting the ocmmand .kind of useless. This should _either_ be fixed by just removing the time, or by adding it to the database and actually showing the time whe n the field got set.

**Comment by 6gk** [comment]
yes

![](https://cdn.discordapp.com/emojis/855255537708695592.png)
