### ISSUE TITLE
[FEATURE ADDITION PETITION] Disallow most common 200 or so english words to be added as a highlight

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#130]
rate limiting lol

plz like and subscribe

**Comment by mlvzk** [comment]
[NLTK's list of english stopwords](https://gist.github.com/sebleier/554280)

**Comment by elkowar** [comment]
why would we go with that vs. something like just http://www.teacherjoe.us/Vocab200.html

**Comment by elkowar** [comment]
@mlvzk

**Comment by mlvzk** [comment]
> why would we go with that vs. something like just http://www.teacherjoe.us/Vocab200.html

@elkowar that's a very bad list, there's `may` but not `maybe` which is more popular than may, at least on the server. They're for beginners to learn so they don't have suffixes or prefixes, which we need if you wanna do a simple equality check, without stemming.

Maybe we should just run a script on the server to collect the most used words from messages

**Comment by legendofmiracles** [comment]
gk already did that once

**Comment by 6gk** [comment]
I didn't.

**Comment by 6gk** [comment]
what I *did* do was check a few words and add the most popular to my hl list.

**Comment by legendofmiracles** [comment]
Oh, misunderstanding. 
Probably still not a very flawed list 🤔 (except for the kiwmi part)

**Comment by 6gk** [comment]
Remind me tomorrow and I might run a script and check some words.  I
think 5k most recent messages in a channel is feasible, I don't think
discord allows you to use the search api for more than 5k, or I might
just check if there's another endpoint.  anyway point is remind me
tomorrow (or don't and do it yourself, idc)

reason is windows™, btw

**Comment by elkowar** [comment]
i mean, I'm pretty sure if i just find the _actual_ 200 most used words in english that should be fine, no?

**Comment by 6gk** [comment]
Almost certainly will be fine, just add stuff like kekw, kek, and a few
other slang/emotes too

**Comment by 6gk** [comment]
(such as lol, lmao, and such)

**Comment by 6gk** [comment]
turns out people are still doing it

mtvare has 113 thousand DMs with him............

**Comment by 6gk** [comment]
@elkowar @mlvzk  probably time to work on it now.
