### ISSUE TITLE
ask user if they want to overwrite their existing fields when they run !setfetch

### ISSUE THREAD

**Issue by mlvzk** [unixporn/robbb#14]
If a user tries to fill out !setfetch manually, they should be prompted if they want to overwrite their current fields, or update them.

Detecting if a user is manually typing out !setfetch fields could be done by checking if the number of fields is less than the number of fields that the fetch.sh script outputs.

**Comment by elkowar** [comment]
This has been discussed again recently (keeping it here for future reference)
![image](https://user-images.githubusercontent.com/5300871/122377028-ffc96500-cf64-11eb-97f8-c85dbc96619c.png)

**Comment by elkowar** [comment]
Slashcommands have now changed the UX such that there isn't a full overwrite anymore, you always just change single fields. Thus, we can close this
