### ISSUE TITLE
[BUG] the fields in !top are bad and unclear

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#141]
# my essay on why rust bad

## Expected behaviour
Works

## Current behaviour
Doesn't work :/

## examples

none of the following work as an argument:
 - `GTK3 Theme` (what is listed in `!top`)
 - `Theme` (what is used in `!setfetch`)
 - `GTK 3 Theme`​
 - `GTK Theme`

# end of essay, thanks for reading and changing your opinion

**Comment by 6gk** [comment]
There should absolutely be aliases

DE/WM = de, wm, dewm

(i still don't know what the proper GTK one is) = gtk, theme, gtk3 theme

("gtk icon theme" is also broken) = icons, gtk icon theme

~~bar = pub~~

~~editor = viitor~~

**Comment by LtPeriwinkle** [comment]
do we want anything aliased other than de/wm and gtk stuff? it isn't too difficult to add more just wondering what i should put in to start with.

**Comment by elkowar** [comment]
Are you working on a PR for this? If so, i'll assign you! @LtPeriwinkle

**Comment by LtPeriwinkle** [comment]
yep!

**Comment by elkowar** [comment]
Would you say this is done, @6gk ?

**Comment by 6gk** [comment]
seems good, ye

closing because of #172

**Comment by 6gk** [comment]
shit wrong thing

oh well lol
