### ISSUE TITLE
[FEATURE] allow tags to contain images

### ISSUE THREAD

**Issue by elkowar** [unixporn/robbb#150]
## proposed feature
!tag tags should be able to contain images.

**Comment by legendofmiracles** [comment]
Why should they be exclusively for images? 
I feel a like it works quite fine right now - with only text
But additionally images would be fine

**Comment by 6gk** [comment]
> or be exclusively images

this works, or at least with singular image.

**Comment by elkowar** [comment]
> > or be exclusively images
> 
> this works, or at least with singular image.

Right, idk why it didn't work

**Comment by undefinedDarkness** [comment]
So does it work or doesnt it

**Comment by elkowar** [comment]
tag that is _only_ an image works, tag that _includes_ an image does not but should

**Comment by 6gk** [comment]
seems to work but it has to be a url

**Comment by 6gk** [comment]
but it also displays as plaintext, so it won't show a date which people assume to be the time of setting (#125)

**Comment by 6gk** [comment]
But yeah

This works, it just has to be a url instead of an attachment   
Also if the first thing is a link then the whole tag is plaintext (which allows embeds & image-only tags without the url visible)

closing
