### ISSUE TITLE
[FEATURE]  !poll should have a 5-scale voting system

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#152]
instead of "yes dontcare no" it should be "heavyyes mildyes dontcare mildno heavyno"

dunno what emotes to do for it though

**Comment by elkowar** [comment]
disagree tbh - that makes actually looking at the result unnecessarily hard, and if you have that much of a nuanced 🧅 then you probably wanna type that out anyways,...
although obviously open for further 🧅s

**Comment by 6gk** [comment]
> that makes actually looking at the result unnecessarily hard

ehhhhhhhhhhhhhhhhhhh fair

> and if you have that much of a nuanced onion

You don't need to have a nuanced opinion to have a strong/weak(but still existent) opinion on something.

Someone who has a strong preference towards an action happening should be more valued more than someone else who has a mild preference towards it not happening.

> then you probably wanna type that out anyways

Discussion in #polls is already annoying enough.  And also that kinda ruins your point that it "makes looking at the result unnecessarily hard".

**Comment by mTvare6** [comment]
This feels more like a rating system than a poll, so maybe !rate 🤔

**Comment by 6gk** [comment]
> This feels more like a rating system than a poll

i guess we've been misusing #polls my bad

It's not often that it's black and white, there is always different levels of preference.
