### ISSUE TITLE
[BUG] setfetch sets version to distro name only on macOS

### ISSUE THREAD

**Issue by mTvare6** [unixporn/robbb#155]
## Expected behaviour
When running `!top distro`, macos should come 9th as its more used that pop!os (according to `!top distro macOS`)

## Current behaviour
The setfetch script [adds version](https://github.com/unixporn/robbb/blob/master/fetcher.sh#L173-L176) to distro name on macos, this makes people fetch have `macos 11.3.1` instead of `macos` which prevent it from coming on !top command

## Solution
Remove it the $ver entirely (Also if possible update every previously set macos fetches to macOS instead of having versions
or have `!top distro macos` someone have `macos 11.3.1` included in count

**Comment by elkowar** [comment]
@6gk could u take a look here? this is a fetcher.sh issue

**Comment by 6gk** [comment]
> setfetch sets version to distro name only on macOS

this is not what happens; closing.


kidding.

I mean, linux includes version too, so things like ubuntu are lower in !top.

This is a !top issue, not a fetcher.sh issue.

**Comment by mTvare6** [comment]
fix top then 😔

**Comment by 6gk** [comment]
@mTvare6 The issue has been closed with a commit.

Take a look on the server :)
