### ISSUE TITLE
[BUG] Allow mods to view highlights of a specific user, and most triggered highlights

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#159]
## Expected behaviour
Works

## Current behaviour
Doesn't work :/

commands can be `!hl list [user]` / `!hl popular`

**Comment by legendofmiracles** [comment]
I'm bored, can this be assigned to me?

**Comment by legendofmiracles** [comment]
Should command proceed silently with the authors highlights if the user isn't a mod? Or rather fail verbosly?

**Comment by 6gk** [comment]
Hm.

I like the vague error similar to what happens when you try add an invalid highlight. ("couldn't do, something went wrong")

So maybe do something similar to that?

**Comment by legendofmiracles** [comment]
I added a small title to the highlights list: 
![image](https://user-images.githubusercontent.com/30902201/124637157-e5561d80-de78-11eb-8574-54fb59d26155.png)

Is this enough? The user will quickly notice that the highlights are from him, and not the mentioned user.
