### ISSUE TITLE
[BUG] Edited messages containing banned word isn't deleted

### ISSUE THREAD

**Issue by mTvare6** [unixporn/robbb#161]
## Expected behaviour
Deletes the edited message containing banned words

## Current behaviour
Only deletes unedited messages with banned word and doesn't after editing it

**Comment by 6gk** [comment]
Also note that "I was testing" is not a valid reason to use a slur, and you won't be treated differently for claiming that.

**Comment by 6gk** [comment]
Also invisible characters should be removed before the regex test.
