### ISSUE TITLE
[BUG] rust bad and slow

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#165]
ban with 20s delay (usually 1s): https://discord.com/channels/635612648934735892/635627296912310283/862497473493991466

warn with 2.8s delay (usually 1s): https://discord.com/channels/635612648934735892/635625925748457482/862514227897827360

help with 5s delay (usually 0.6s): https://discord.com/channels/635612648934735892/655947537538088962/862518939435139082

**Comment by 6gk** [comment]
18s !fetch -- https://discord.com/channels/635612648934735892/655947537538088962/893113991839248445

9.3s !fetch -- https://discord.com/channels/635612648934735892/655947537538088962/893138165509017610

**Comment by elkowar** [comment]
this should probably be fixed by e6f9da94fee45df19e6954275576c0193d0ca4e4
I'll close this, if it comes up again, please reopen

**Comment by elkowar** [comment]
Has this been an issue since?

**Comment by 6gk** [comment]
idk i've been deaded

**Comment by 6gk** [comment]
Mr. r[edacted] has heard my attempts at publicizing his murder, so he
went after me!  I escaped by the skin of my teeth, so I went into
hiding.

**Comment by elkowar** [comment]
oh no
I'll close this issue until anything happens again!

**Comment by 6gk** [comment]
Look at this blatant disregard for the safety of his peers!
