### ISSUE TITLE
[REFACTOR] use an enum for fetch fields

### ISSUE THREAD

**Issue by elkowar** [unixporn/robbb#172]
Currently, it's somewhat confusing to deal with the different fetch fields and their names in the code. Thus, it would be a good idea to have an explicit enum listing all the available fetch fields, and to use that typed representation instead of relying on strings everywhere. This would also allow for storing the fetch fields in a `HashMap<FetchField, String>`

**Comment by LtPeriwinkle** [comment]
Could implement `TryFrom<&str>` for `FetchField` to easily get field aliases working as well. Also, what would be the plan for the database values that already exist? since there are currently spaces in some fetch field names, I don't think serde would be able to figure them into an enum variant.

**Comment by elkowar** [comment]
Worst case, we'd just do a custom serializer and deserializer 🤷🏻

**Comment by elkowar** [comment]
Implemeneted in #194
