### ISSUE TITLE
[FEATURE] Make highlights have a whitelist instead of a blocklist

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#173]
abuse (rate limiting), performance are issues with the current system.

Mods/Interns should be allowed to ignore the whitelist because highlights are a rather useful feature for moderation.

[suggested by cactus]

**Comment by 6gk** [comment]
also should this be a file or a command?

i'd prefer a command as it's easier to update and won't require restarting the bot.

**Comment by elkowar** [comment]
not really a fan of this tbh. I feel like we should first try to find other solutions than this massive restriction of how useful it is.

many people highligh their own names, which should be more than fine. Performance issues should better be solved by implementing rate limiting and/or optimizing the performance in general. Not sure if we're _actually_ running into ratelimiting here, has anyone actually verified that there is a shared rate limit between DMs and the server?
