### ISSUE TITLE
[BUG] !emojistats doesn't show least used emotes

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#177]
least used emotes are a lot more useful than most used as when we have no slots, it allows us to see what can be removed.

**Comment by 6gk** [comment]
@AusCyberman fix™

**Comment by AusCyberman** [comment]
I said this to elko and he was like no don't do that.
so do you want to have it as either an option to it, or a completely separate thing

**Comment by 6gk** [comment]
An option would be nice, but the way I see it is not supporting showing the least used server emotes makes this feature practically useless for the aforementioned reason.

**Comment by AusCyberman** [comment]
> 
> 
> An option would be nice, but the way I see it is not supporting showing the least used server emotes makes this feature practically useless for the aforementioned reason.

so now i have to readd my code, which did that anyway after elko was like no

**Comment by elkowar** [comment]
lol didn't plan to close yet, sorry
