### ISSUE TITLE
[BUG] !emojistats counts reactions multiple times, and counts the command when checking.

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#178]
Regardless of how many people react, it should only increase by one per message.

So if 20 people react :this: to **one** message, it should only increase by one reaction.

Also if someone removes/re-adds their reaction to a message, it adds another to the counter without decreasing it.

---

and running `!emojistats :this:` increases the counter, which sounds a tad unintuitive and imo would misrepresent the usage.

**Comment by AusCyberman** [comment]
> Regardless of how many people react, it should only increase by one per message.
> 
> So if 20 people react :this: to **one** message, it should only increase by one reaction.
> 
> Also if someone removes/re-adds their reaction to a message, it adds another to the counter without decreasing it.
> 
> and running `!emojistats :this:` increases the counter, which sounds a tad unintuitive and imo would misrepresent the usage.

Why only one per reaction?

**Comment by 6gk** [comment]
> Why only one per reaction?

When one person reacts something, other people are *significantly*
more likely to press the button, even if they'd never add the reaction
themself.

In other words, non-first reactions are ""worth"" [for lack of a
better word] significantly less.  Especially (**but not exclusively**)
in showcase/rules/announcements and other slow-moving channels.

**Comment by AusCyberman** [comment]
> Why only one per reaction?
> When one person reacts something, other people are *significantly* more likely to press the button, even if they'd never add the reaction themself. In other words, non-first reactions are ""worth"" [for lack of a better word] significantly less. Especially (**but not exclusively**) in showcase/rules/announcements and other slow-moving channels.

To add a counter argument, how about only doing it once for showcase/rules/announcments but for every other one it matters?, because otherwise its a bit of a performance hit

**Comment by 6gk** [comment]
> because otherwise its a bit of a performance hit

tbh i didn't even consider performance.  Yeah I dunno then.
------
> Also if someone removes/re-adds their reaction to a message, it adds another to the counter without decreasing it.

context-ish: https://discord.com/channels/635612648934735892/655947537538088962/864300080084942869

[for reference, guyman was spam clicking the nixos react after I did
the initial react - it went up for every one I did]

**Comment by AusCyberman** [comment]
> because otherwise its a bit of a performance hit
> tbh i didn't even consider performance. Yeah I dunno then. ------
actually, it should hopefully be all good, you just have to search through all reactions which could be a hassle, but i hope it shouldn't be
> Also if someone removes/re-adds their reaction to a message, it adds another to the counter without decreasing it.
Doing that right now
> context-ish: https://discord.com/channels/635612648934735892/655947537538088962/864300080084942869 [for reference, guyman was spam clicking the nixos react after I did the initial react - it went up for every one guyman did]

y

**Comment by AusCyberman** [comment]
Okay essentially all done with this one

**Comment by AusCyberman** [comment]
Okay essentially all done with this one

**Comment by elkowar** [comment]
@6gk art you happ. With the fixes? If so, feel free to close this 👍

**Comment by 6gk** [comment]
already gave approval, forgot to close issue

![image](https://user-images.githubusercontent.com/40295114/125913640-407a6b2c-b624-472a-8ec9-4fd40442a97f.png)
