### ISSUE TITLE
[BUG] user matching with `user#1234` doesn't work

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#182]
## Expected behaviour
Works

## Current behaviour
Doesn't work :/

ie `!fetch gk#7186` should look for the user "gk" with the number "7186", and not a user with the (nick|user)name "gk#7186"

**Comment by undefinedDarkness** [comment]
Can `#` come in any place other than as in this way?

**Comment by 6gk** [comment]
# is allowed in nicknames, but not usernames.

so `gk#7186` is a valid nickname, but i don't think it's even worth
checking nicknames for - similar to ids, as `199492634438270977`
should also be a valid nickname (and username i guess maybe?).

and you could probably just do `#[0-9]{4}$` as a regex match
