### ISSUE TITLE
[FEATURE] automatically rename hoisted names

### ISSUE THREAD

**Issue by mlvzk** [unixporn/robbb#186]
## Is your feature request related to a problem? Please describe.
less work for mods

## Proposed feature
When the bot starts, cycle through all members, detect hoisted names and remove the hoisting prefix from their name.
Listen on [GuildMemberUpdateEvent](https://docs.rs/serenity/0.10.8/serenity/model/event/struct.GuildMemberUpdateEvent.html), detect hoisted names and remove the hoisting prefix from their name.

## Additional info
Why not remove their nickname instead of renaming? Because some users have a hoisting prefix in their Discord username.

**Comment by 6gk** [comment]
common hoist characters are `!"#$'()*+-./` fwiw

(i think that's the order but i cbf to check again)

**Comment by elkowar** [comment]
implemented in #195
