### ISSUE TITLE
Add fetch: Browser

### ISSUE THREAD

**Issue by C47F15H** [unixporn/robbb#197]
## Description 
Add web browsers to Unixporn !top

## Use-case
many users have requested for it in the Discord server.

![image](https://user-images.githubusercontent.com/80169337/128586849-3e928212-97ab-4df7-820f-926ed054bf34.png)
(made with Carl Bot embed maker)

**Comment by 6gk** [comment]
You're asking the wrong question.

What you want is to add browsers to fetch - and it'd have to be a manual
thing as there is no viable way to detect it -- $BROWSER is rarely used,
people tend to have multiple installed, and whatever xdg-open does is often
the wrong one.
I guess technically process checking is an option, but ehhhh, it's also not
too uncommon for people to have multiple open, but if we *must* have it be
automatic i'd do this one.

**Comment by C47F15H** [comment]
idk, many people asked for it in the server that might be set by !setfetch command

**Comment by 6gk** [comment]
yeah no shit

what i'm saying is you want it to be added to fetch, !top is a subset of fetch.
