### ISSUE TITLE
Editing & Undoing for warns and notes

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#2]
by elkowar: https://github.com/unixporn/trup/issues/58

The warn and note commands should have a !note undo <user> / !warn undo <user> command to remove the latest warn / note.

lidl:

> Instead of !note undo I think it would be better to do !note undo <note_id>. For this we would need !note to show notes together with their IDs, but the IDs are pretty long so we should just show the last 3 or 4 characters and use that in !note undo <note_id>

**Comment by elkowar** [comment]
for now we have `!note undo <name>` which undoes the latest note (and the same for warn). I'm not sure if ID stuff is actually necessary - when would you want to remove another note than the last one?

**Comment by 6gk** [comment]
probably fixed by !note undo but that doesn't unlog mutes but meh
