### ISSUE TITLE
[BUG] invalid submision detected when starting a thread in showcase

### ISSUE THREAD

**Issue by umgbhalla** [unixporn/robbb#209]
## Expected behaviour
<#id-of-ricing-theming-channel>
shoudn't ping , i just made a thread

## Current behaviour
![image](https://user-images.githubusercontent.com/67634565/131224756-5fd9c170-84dd-4289-8fa0-38e4dfaab99d.png)

**Comment by ziadomalik** [comment]
Took care of that, making a new PR

**Comment by 6gk** [comment]
i think this was fixed?
