### ISSUE TITLE
[BUG] Updating role colors is painfully slow.

### ISSUE THREAD

**Issue by BrentBoyMeBob** [unixporn/robbb#210]
## Expected behaviour
Often times, whenever I used !role, it would just remove a role and then add a new one instantaneously. 

## Current behaviour
For some reason, the bot takes an extremely long time to update and remove roles now, good 2 minutes AT LEAST, to an extent where it seems to be scrambling each of the roles out of order, adding new ones without clearing the current roles, and clearing the roles after it's even taken effect. This isn't necessarily a large issue, but it seems so odd that it's doing this out of the blue once threads were introduced.

**Comment by mTvare6** [comment]
I suspect rust is doing something to the bot

**Comment by BrentBoyMeBob** [comment]
Just tested it, it seems like the bot has been going much faster all the sudden, not as fast as before, but definitely much more usable.
