### ISSUE TITLE
[BUG] !emojistats is usable by everyone, when it should be mod-only

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#251]
The most use it's gotten is encouraging spam, it should be locked to mods so hopefully it is less of an issue.  
If that doesn't work, the command should be removed.

**Comment by elkowar** [comment]
Would need more onions on that from others

**Comment by 6gk** [comment]
Emote spam, both reaction and text.

And everywhere.  #bot, #lounge, #off-topic, /etc/, /var/, #voice-text, usually not even in a thread.
