### ISSUE TITLE
[BUG] rust does a bad when fetching

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#267]
![image](https://user-images.githubusercontent.com/40295114/138385228-8e341dc2-1eb5-45d8-9e6a-292380138cde.png)

**Comment by 6gk** [comment]
nevermind this is just another rust bad thing

![image](https://user-images.githubusercontent.com/40295114/138386257-ed52ffee-09c6-4881-8fba-e319817a68c7.png)

**Comment by elkowar** [comment]
Shouldn't be a problem anymore
