### ISSUE TITLE
Outside of #bot, Autoremove bot error messages after a few seconds

### ISSUE THREAD

**Issue by eepykate** [unixporn/robbb#3]
by elkowar: https://github.com/unixporn/trup/issues/57

when you mistype a command, in many cases the bot prints the usage string. This response should get automatically removed after some time (~10 seconds).
This could also be done for "Success" style responses.
For this, there should probably be a new function `SendAutoremove` (or something like that) created in command.go, which resembles `Reply`, just that it automatically removes the message after a given amount of time.

**Comment by 6gk** [comment]
\>command.go
\>rust

i totally didn't just copypaste this from the linked issue without putting any thought into it.

**Comment by elkowar** [comment]
Even better: Error messages are now ephemeral, so they won't get shown to others at all
