### ISSUE TITLE
[FEATURE] !ban should support user selection like the rest of the commands do

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#306]
with a confirm button, ideally.

just makes it much easier dealing with user reports of spam bots.

**Comment by 6gk** [comment]
making these types of issues high priority because we have been getting a lot of spam bots recently

**Comment by elkowar** [comment]
With slash commands, this is now a thing

**Comment by 6gk** [comment]
Is it possible to ban members not in the server btw?  using either the user#1234 or snowflake.

**Comment by elkowar** [comment]
shoooooould work, although I haven't tested :eyes:
