### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by willeccles** [unixporn/robbb#308]
## Expected behaviour
bot good

## Current behaviour
bot bad

50+ open issues smh my head bro

**Comment by 6gk** [comment]
I am agreement.

**Comment by 6gk** [comment]
agkreement*

**Comment by druskus20** [comment]
reee

**Comment by elkowar** [comment]
Wrong, there's not 50+ issues anymore!

**Comment by willeccles** [comment]
That can be fixed.
