### ISSUE TITLE
[FEATURE] add 'gk' exception to the 3 character highlight requirement

### ISSUE THREAD

**Issue by 6gk** [unixporn/robbb#322]
also i think reducing the general limit to 2 will be bad:tm: (and will require a lot of stuff to be added to the bad list)

**Comment by 6gk** [comment]
![image](https://user-images.githubusercontent.com/40295114/147062231-51658bba-4240-4b51-9caa-5d122e724d70.png)

alternatively

**Comment by druskus20** [comment]
No never!

**Comment by 6gk** [comment]
racist
