### ISSUE TITLE
Special Request

### ISSUE THREAD

**Issue by circutrider21** [unixporn/robbb#372]
Sorry to bother you, but I was wondering if you knew the usernames of the discord mods, so that I may talk to them. I got banned (my brother was on my PC, screwing around), and somehow got me banned for scamming???

anyways, any help would be appreciated :-)
uiop#8415

**Comment by snakedye** [comment]
Click this [link](scam.com) for free nitro!!!

**Comment by snakedye** [comment]
Shit, sorry my brother was just sending nitro scam on github?!?!!? damn kid screwing around.

**Comment by circutrider21** [comment]
Dang, must be tough

**Comment by druskus20** [comment]
This is a stupid request. 
First of all, this has to be the most classic excuse when asking for an unban. Unless you can somehow provide proof of it, this shouldn't even be considered. Doing so would set a bad precedent for other people asking for similar things.

Second, Github is not the place for this, and more specifically, this repo. This repo is for the bot of the server, not even for the UP organization. GitHub is not an inbox where you should post this kind of request. 
In UP there is a Modmail bot to which you can, among others, send requests related to your personal account. Furthermore, I agree that it is very easy to create an alt account in discord, but that is one more reason to contact the mods through that platform.  There's also a subreddit, you would probably be able to find some discord mods in there. 

You were banned for breaking the rules, and if it really was your brother, sorry but we can / should do nothing.

However, even if I maintain the bot, I'm not a mod so I might be wrong in any of this.

**Comment by circutrider21** [comment]
@druskus20  while I thank you for you sane reply/judgement, I prefer this issue be left alone, since I have not only moved on from r/unixporn as a whole, I also realized how gettting unbanned is kinda futile and this isn't the place to ask, hence, I closed the issue.
