### ISSUE TITLE
[BUG] Memory conversion is incorrect

### ISSUE THREAD

**Issue by GlowingUmbreon** [unixporn/robbb#383]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/unixporn/robbb/issues?q=is%3Aissue) and made sure that this is not a duplicate

### Expected behaviour

The conversion the bot does with the script should result in the correct memory size.

### Current Behaviour

The conversion the bot does with the script is incorrect and results in a incorrect memory size.

### Other info

`/proc/meminfo` (what the script uses) outputs the memory size in **kibibytes** but has the extension `kb`, when the command is run the bot sees `kb` and thinks it means **kilobytes** and thus the incorrect conversion is made resulting in a inaccurate memory size.

**Comment by elkowar** [comment]
Do you have a source for /proc/meminfo being kibibytes? I haven't been able to confirm that

**Comment by buffet** [comment]
From a quick search (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-proc-meminfo) it appears as though `kB` refers to kilobytes (1000 bytes) in this case.

This is also consistent with other APIs, where `KB` is usually used for kibibytes (1024 bytes).

**Comment by elkowar** [comment]
I guess then we can close this
