### ISSUE TITLE
[FEATURE] Check common clearly unintentional matches in blocklist regex when adding

### ISSUE THREAD

**Issue by buffet** [unixporn/robbb#420]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/unixporn/robbb/issues?q=is%3Aissue) and made sure that this is not a duplicate

### Is your feature request related to a problem? Please describe.

At the moment mods can make mistakes and accidentally add regex that match the empty string, when adding to the blocklist.

### Proposed feature

Check first.

### Additional context

I don't think this will ever happen in practice, but better be safe than sorry.

**Comment by elkowar** [comment]
1. This is the perfect issue to be 420
2. "common accidental matches" I'd just say let's check we don't match empty strings, and then add a few tests for random long texts that should never be blocked just to verify no other dumb thing (I. E. (`...`) matching any msg > 2 characters) happens
