### ISSUE TITLE
!fetch can't search for users with spaces in username/nickname

### ISSUE THREAD

**Issue by mlvzk** [unixporn/robbb#48]
![image](https://user-images.githubusercontent.com/44906333/112735218-dd6a1180-8f4a-11eb-8f5a-73528923327b.png)

**Comment by elkowar** [comment]
You can quote, or rely on the disambiguation thingy and just `!fetch Kanye`,...
Given that we support `!fetch Kanye Distro`, it'd be hard to tell when you want the field and when it's a multi-word name,...
Do you think a separate syntax for field may be preferrable?

**Comment by legendofmiracles** [comment]
This works if you pass the argument in "".
![image](https://user-images.githubusercontent.com/30902201/112762890-abf85100-8ff1-11eb-9324-92e42cb84fb0.png)

The same also applies to when trying to run `!top GTK3 Theme`

**Comment by mlvzk** [comment]
Maybe the error message could be changed, for example to `Did you mean to search for user "Kanye Cube"? If so, use **!fetch "Kanye Cube"**`?
Another idea is changing syntax for fetching fields to `!fetch some person -Distro`, with the minus sign. You could even allow multiple fields to do `!fetch someone -Git -Dotfiles`

**Comment by elkowar** [comment]
What if we made it `!fetchfield` explicitly? i'm not really a fan of just doing minuses, that's kinda confusing imo...
Changing the message would be weird if it's like
`Did you mean to search for user "Elkowar Disrto"? if so, use **!fetch "Elkowar Disrto"**`,...
maybe if i just edit the help to explicitly highlight the quotes?
(as in, that the help just includes the quotes?)

**Comment by mlvzk** [comment]
!fetchfield would be fine

**Comment by elkowar** [comment]
ig !fetchfield would have the exact same issue tho, it would still require the quotes,....
Imo the best solution would just be to make the quotes more visible in the help

or, we could start getting into doing `fetch <user> --field <field>` stuff, but _ehhhhhhhhh_ that might be cringe?

**Comment by mlvzk** [comment]
can we disable this `field` feature for now?

**Comment by elkowar** [comment]
we can, but,... I like it :( Imma just ask the community real quick!
