### ISSUE TITLE
Wallpaper command

### ISSUE THREAD

**Issue by snakedye** [unixporn/robbb#56]
Wallpapers would be submitted like this:
```
!wallpaper <url>
tag1, tag2, ....
```
You could get a list of wallpapers filtered by tags like this: 
`!wallpaper tag1, tag2, ...`

**Comment by elkowar** [comment]
wouldn't the list of wallpapers quickly get _very_ large? I see some issues with that, honestly,... especially because it's images, we couldn't easily just embed those directly, making the search kinda useless, no?
What would this offer over just searching for the tags in discord search?

**Comment by snakedye** [comment]
Tag words like nord, gruvbox, come more often than not in conversation instead of tags so if you search something, you have to look through a lot of convo irrelevant instead of what you're actually looking for. 

Searching for tags also become nearly impossible for more than one keywords. Discord just doesn't show any result.

>wouldn't the list of wallpapers quickly get very large

Yes but I don't think they all to be shown when the they're fetched. Maybe the 10 most recents or more popular than if there's more provide a link where the user can look at the entire list of wallpapers.

**Comment by 6gk** [comment]
I don't think `in:wallpapers tags [...]` has the issue you're describing, you sure you're not just searching `[...]` without anything more specific?
