### ISSUE TITLE
[FEATURE] Automatically sort emotes based on usage, to avoid popular ones getting axed when boost level falls

### ISSUE THREAD

**Issue by davidv171** [unixporn/robbb#76]
## Is your feature request related to a problem? Please describe.
The problem being that some emotes, even though they are newer are infinitely more popular. So when boost level drops, a really popular emote could be axed. 
## Proposed feature
Given how we already have our top guys working on #16 , this new feature could be implemented to re-arrange the emotes, which is an absolute pain to do manually. 

## Additional context
Well, some admins/mods might want to vouch for a few emotes they personally want. It's up to them to decide if they want to give possibilities of "immutability" to certain emotes. Those emotes would not be sorted based on their popularity.

**Comment by 6gk** [comment]
tbh i'm very against this because it requires deleting and re-adding emotes a lot

it also breaks searching, emote stat logging, and history

and there's a rate limit of 50 emote actions per hour per server

**Comment by 6gk** [comment]
just boost us nerd
